# Generated by Django 3.2.6 on 2021-08-15 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 11, 43, 59, 888648)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='list_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
